/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CalendarUpdateRequest
 */
export interface CalendarUpdateRequest {
    /**
     * 
     * @type {number}
     * @memberof CalendarUpdateRequest
     */
    'tenantid': number;
    /**
     * 
     * @type {number}
     * @memberof CalendarUpdateRequest
     */
    'eventid': number;
    /**
     * 
     * @type {number}
     * @memberof CalendarUpdateRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof CalendarUpdateRequest
     */
    'status': string;
}

