/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { CompletedEventResponse } from './completed-event-response';

/**
 * 
 * @export
 * @interface CompletedEventsResponse
 */
export interface CompletedEventsResponse {
    /**
     * 
     * @type {Array<CompletedEventResponse>}
     * @memberof CompletedEventsResponse
     */
    'completeEvents': Array<CompletedEventResponse>;
}

