/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateParticipantGuest
 */
export interface CreateParticipantGuest {
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantGuest
     */
    'eventcode': string;
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantGuest
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantGuest
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof CreateParticipantGuest
     */
    'email': string;
}

