/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface CreateUsersRequest
 */
export interface CreateUsersRequest {
    /**
     * 
     * @type {string}
     * @memberof CreateUsersRequest
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUsersRequest
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUsersRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUsersRequest
     */
    'invitationcode'?: string;
    /**
     * 
     * @type {number}
     * @memberof CreateUsersRequest
     */
    'tenantid'?: number;
    /**
     * 
     * @type {string}
     * @memberof CreateUsersRequest
     */
    'status'?: string;
}

