/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface DisableUserAccount
 */
export interface DisableUserAccount {
    /**
     * 
     * @type {number}
     * @memberof DisableUserAccount
     */
    'userid': number;
    /**
     * 
     * @type {boolean}
     * @memberof DisableUserAccount
     */
    'disableStatus': boolean;
    /**
     * 
     * @type {number}
     * @memberof DisableUserAccount
     */
    'tenantid'?: number;
}

