/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ExhibitResponse
 */
export interface ExhibitResponse {
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'tenantid': number;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'status': string;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'mimetype': string;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'previewlink': string;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'partyname': string;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'uploadedby': string;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'filesize'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'updatedat'?: number;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'objectid': number;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'partyid': number;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof ExhibitResponse
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'eventid': number;
    /**
     * 
     * @type {number}
     * @memberof ExhibitResponse
     */
    'userid': number;
}

