/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParticipantLinkResponse
 */
export interface ParticipantLinkResponse {
    /**
     * 
     * @type {string}
     * @memberof ParticipantLinkResponse
     */
    'participantLink': string;
    /**
     * 
     * @type {string}
     * @memberof ParticipantLinkResponse
     */
    'participantKey': string;
}

