/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.6
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface StipulationChangeRequest
 */
export interface StipulationChangeRequest {
    /**
     * 
     * @type {number}
     * @memberof StipulationChangeRequest
     */
    'eventid': number;
    /**
     * 
     * @type {number}
     * @memberof StipulationChangeRequest
     */
    'partyid': number;
    /**
     * 
     * @type {string}
     * @memberof StipulationChangeRequest
     */
    'stipulationstatus': StipulationChangeRequestStipulationstatusEnum;
    /**
     * 
     * @type {number}
     * @memberof StipulationChangeRequest
     */
    'stipulationupdatedby'?: number;
    /**
     * 
     * @type {string}
     * @memberof StipulationChangeRequest
     */
    'stipulationupdatedat'?: string;
}

export const StipulationChangeRequestStipulationstatusEnum = {
    Waiting: 'WAITING',
    Agreed: 'AGREED',
    Disagreed: 'DISAGREED'
} as const;

export type StipulationChangeRequestStipulationstatusEnum = typeof StipulationChangeRequestStipulationstatusEnum[keyof typeof StipulationChangeRequestStipulationstatusEnum];


