/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateParticipantRole
 */
export interface UpdateParticipantRole {
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRole
     */
    'id': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRole
     */
    'eventid': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateParticipantRole
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateParticipantRole
     */
    'role': UpdateParticipantRoleRoleEnum;
}

export const UpdateParticipantRoleRoleEnum = {
    Attending: 'ATTENDING',
    Scheduling: 'SCHEDULING',
    Guest: 'GUEST',
    Witness: 'WITNESS'
} as const;

export type UpdateParticipantRoleRoleEnum = typeof UpdateParticipantRoleRoleEnum[keyof typeof UpdateParticipantRoleRoleEnum];


