/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateEventRequest
 */
export interface UpdateEventRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'matterid': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'eventtype': UpdateEventRequestEventtypeEnum;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'datestart'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'timezone'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'duration'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'status': UpdateEventRequestStatusEnum;
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'tenantid': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateEventRequest
     */
    'stipulation'?: string;
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'stipulationobjectid'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'invited': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateEventRequest
     */
    'exhibit': number;
}

export const UpdateEventRequestEventtypeEnum = {
    Deposition: 'Deposition',
    Hearing: 'Hearing',
    Arbitration: 'Arbitration'
} as const;

export type UpdateEventRequestEventtypeEnum = typeof UpdateEventRequestEventtypeEnum[keyof typeof UpdateEventRequestEventtypeEnum];
export const UpdateEventRequestStatusEnum = {
    Draft: 'DRAFT',
    Scheduled: 'SCHEDULED',
    InProgress: 'IN_PROGRESS',
    Preflight: 'PREFLIGHT',
    Complete: 'COMPLETE',
    Cancelled: 'CANCELLED',
    Archive: 'ARCHIVE',
    ArchiveComplete: 'ARCHIVE_COMPLETE'
} as const;

export type UpdateEventRequestStatusEnum = typeof UpdateEventRequestStatusEnum[keyof typeof UpdateEventRequestStatusEnum];


