/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateParticipantRequest
 */
export interface UpdateParticipantRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRequest
     */
    'eventid': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRequest
     */
    'partyid': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRequest
     */
    'userid': number;
    /**
     * 
     * @type {string}
     * @memberof UpdateParticipantRequest
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateParticipantRequest
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateParticipantRequest
     */
    'email': string;
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRequest
     */
    'tenantid': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateParticipantRequest
     */
    'id': number;
    /**
     * 
     * @type {boolean}
     * @memberof UpdateParticipantRequest
     */
    'isEmailSent': boolean;
}

