/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateSpeakerNameRequest
 */
export interface UpdateSpeakerNameRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdateSpeakerNameRequest
     */
    'eventid': number;
    /**
     * 
     * @type {number}
     * @memberof UpdateSpeakerNameRequest
     */
    'tenantid': number;
    /**
     * 
     * @type {Array<string>}
     * @memberof UpdateSpeakerNameRequest
     */
    'speakernames': Array<string>;
}

