/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdatePartyRequest
 */
export interface UpdatePartyRequest {
    /**
     * 
     * @type {number}
     * @memberof UpdatePartyRequest
     */
    'eventid': number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'name': string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'firstname'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'lastname'?: string;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'partytype': string;
    /**
     * 
     * @type {number}
     * @memberof UpdatePartyRequest
     */
    'tenantid': number;
    /**
     * 
     * @type {string}
     * @memberof UpdatePartyRequest
     */
    'invitationcode': string;
    /**
     * 
     * @type {number}
     * @memberof UpdatePartyRequest
     */
    'id': number;
}

