/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UpdateMatterRequest
 */
export interface UpdateMatterRequest {
    /**
     * 
     * @type {string}
     * @memberof UpdateMatterRequest
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof UpdateMatterRequest
     */
    'description': string;
    /**
     * 
     * @type {number}
     * @memberof UpdateMatterRequest
     */
    'tenantid'?: number;
    /**
     * 
     * @type {number}
     * @memberof UpdateMatterRequest
     */
    'id': number;
}

