/* tslint:disable */
/* eslint-disable */
/**
 * Skrib
 * Skrib
 *
 * The version of the OpenAPI document: 2.11.7
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface UserResponse
 */
export interface UserResponse {
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'tenantid': number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'status': string;
    /**
     * 
     * @type {boolean}
     * @memberof UserResponse
     */
    'disablestatus': boolean;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'role': string;
    /**
     * 
     * @type {number}
     * @memberof UserResponse
     */
    'id': number;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'firstname': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'lastname': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof UserResponse
     */
    'invitationcode'?: string;
}

