export const SAVE_SEARCH_TEXT = 'SAVE_SEARCH_TEXT';
export const GET_SEARCH_TEXT = 'GET_SEARCH_TEXT';
export const GET_SEARCH_MATTER_ID = 'GET_SEARCH_MATTER_ID';
export const SAVE_SEARCH_MATTER_ID = 'SAVE_SEARCH_MATTER_ID';
