/* tslint:disable */
/* eslint-disable */
/**
 * Skribe Authentication Endpoints
 * Endpoints used during the authentication, session verification or user creation processes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import { EmployeCount } from './employe-count';

/**
 * 
 * @export
 * @interface CreateUser
 */
export interface CreateUser {
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'firstName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'lastName': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'title': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'company': string;
    /**
     * 
     * @type {EmployeCount}
     * @memberof CreateUser
     */
    'employees': EmployeCount;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'country': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'state'?: string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'phone': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'email': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'recaptcha': string;
    /**
     * 
     * @type {string}
     * @memberof CreateUser
     */
    'invitationCode'?: string;
}

