/* tslint:disable */
/* eslint-disable */
/**
 * Skribe Authentication Endpoints
 * Endpoints used during the authentication, session verification or user creation processes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface GetParticipant
 */
export interface GetParticipant {
    /**
     * 
     * @type {string}
     * @memberof GetParticipant
     */
    'token': string;
    /**
     * 
     * @type {string}
     * @memberof GetParticipant
     */
    'key': string;
}

