/* tslint:disable */
/* eslint-disable */
/**
 * Skribe Authentication Endpoints
 * Endpoints used during the authentication, session verification or user creation processes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ParticipantResponse
 */
export interface ParticipantResponse {
    /**
     * 
     * @type {string}
     * @memberof ParticipantResponse
     */
    'token'?: string;
    /**
     * 
     * @type {number}
     * @memberof ParticipantResponse
     */
    'eventId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantResponse
     */
    'participantId'?: number;
    /**
     * 
     * @type {number}
     * @memberof ParticipantResponse
     */
    'partyId'?: number;
    /**
     * 
     * @type {string}
     * @memberof ParticipantResponse
     */
    'dateStart'?: string;
}

