/* tslint:disable */
/* eslint-disable */
/**
 * Skribe Authentication Endpoints
 * Endpoints used during the authentication, session verification or user creation processes.
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * The identity provider
 * @export
 * @enum {string}
 */

export const Provider = {
    Email: 'email',
    Oidc: 'oidc',
    Saml: 'saml',
    Google: 'google',
    Twitter: 'twitter',
    Facebook: 'facebook',
    Microsoft: 'microsoft',
    Apple: 'apple',
    Linkedin: 'linkedin',
    Yahoo: 'yahoo',
    Play: 'play',
    Github: 'github',
    Phone: 'phone',
    Anonymous: 'anonymous'
} as const;

export type Provider = typeof Provider[keyof typeof Provider];



