export enum AcceptedMimeTypes {
  ApplicationPdf = 'application/pdf',
  ApplicationMsword = 'application/msword',
  ApplicationVndOpenxmlformatsOfficedocumentWordprocessingmlDocument = 'application/vnd.openxmlformats-officedocument.wordprocessingml.document',
  VideoXMsvideo = 'video/x-msvideo',
  ImageBmp = 'image/bmp',
  ImageGif = 'image/gif',
  TextHtml = 'text/html',
  ImageJpeg = 'image/jpeg',
  AudioMpeg = 'audio/mpeg',
  VideoMp4 = 'video/mp4',
  VideoMpeg = 'video/mpeg',
  ImagePng = 'image/png',
  ApplicationVndMsPowerpoint = 'application/vnd.ms-powerpoint',
  ApplicationVndOpenxmlformatsOfficedocumentPresentationmlPresentation = 'application/vnd.openxmlformats-officedocument.presentationml.presentation',
  TextPlain = 'text/plain',
  VideoWebm = 'video/webm',
  ApplicationVndMsExcel = 'application/vnd.ms-excel',
  ApplicationVndOpenxmlformatsOfficedocumentSpreadsheetmlSheet = 'application/vnd.openxmlformats-officedocument.spreadsheetml.sheet',
}
